### ISSUE TITLE
timestamps sometimes incorrect and alternate between accurate and incorrrect

### ISSUE THREAD

**Issue by mueslimak3r** [mueslimak3r/tv-intro-detection#12]
**Copied discussion from #7 by @fallenbagel**

Upon testing what I could for now, which is batman: the animated series, its now detecting the intro to start at 0:05:36 and end at 0:06:41 for some episodes whereas the actual intro starts at 0:00:00 and ends around 0:01:05. At first I thought it was just one mistake but it seems like every other episode is being misidentified thinking (some episodes seems to be identified correctly). I checked out the timestamps and there doesn't seem to be any identical footage there. Let me run the script again to confirm whether the same thing happens.

EDIT: nope. Same thing happening I wonder why thinking
Its literally doing it alternatively. 1st episode has the wrong, 2nd episode has the correct one, 3rd wrong, 4th correct, 5th wrong, 6th correct.....etc

Season 1

![162330894-0349f843-0bfd-4418-92ed-dd7477ccf136](https://user-images.githubusercontent.com/28824542/162345623-5f1be62f-80f8-4ea9-b3e1-2df0d704c393.png)

**Comment by mueslimak3r** [comment]
with S01E01 & E02 as examples, is it reprocessing either of those?

I've seen this before too where it alternates between two almost identical times, but it was when testing some code that didn't end up working.

**Comment by mueslimak3r** [comment]
I pushed some changes that fix videos not being skipped if they can't be found. Perhaps the changes fix this too?

**Comment by Fallenbagel** [comment]
> with S01E01 & E02 as examples, is it reprocessing either of those?

Do you mean when I reran from scratch? if so it seems to still end up doing the same thing. Alternating

> I pushed some changes that fix videos not being skipped if they can't be found. Perhaps the changes fix this too?

Let me test it out. I'm gonna run without rclone media and test whether it happens on other series then run again with rclone media to test whether it only happens in batman. I'll get back to you in like an hour

**Comment by mueslimak3r** [comment]
To test specific seasons/folders you can run `decode.py` directly

**Comment by Fallenbagel** [comment]
> To test specific seasons/folders you can run `decode.py` directly

Wouldn't that not create a json file which stores rhe timestamps? 🤔

**Comment by mueslimak3r** [comment]
> > To test specific seasons/folders you can run `decode.py` directly
> 
> Wouldn't that not create a json file which stores the timestamps? 🤔

Yeah it won't make json. But with the `-d` (debug logging) or `-l` (debug logging to file) flags you can still get logs to tell if it's working

**Comment by Fallenbagel** [comment]
> Yeah it won't make json. But with the `-d` (debug logging) or `-l` (debug logging to file) flags you can still get logs to tell if it's working

OH you mean the timestamps?

Also I tested on fresh prince. That alternate thing did not happen (altho it did misidentify a few where one was way off, the other finished too early and the other lasted 1 second) so let me test on batman and see if the alternative thing happens again.
![image](https://user-images.githubusercontent.com/98979876/162369684-bdd7de1c-71ca-4e70-95f4-5a597236864d.png)

**Comment by mueslimak3r** [comment]
I have Batman The Animated Series so I'll see if I get the same results.

Regarding the results from the fresh prince, it looks like that output isn't from the final result. S01E04 has start 0:00:00 end 0:00:01 which should only show prior to the "error correction" stage.

If the final result had a duration that short it should show something like this:
<img width="741" alt="Screen Shot 2022-04-07 at 11 05 21 PM" src="https://user-images.githubusercontent.com/28824542/162374588-a017d30b-fa8e-4de9-9652-1d9999f69daa.png">

If you could post the full log for both of those that would be helpful

**Comment by mueslimak3r** [comment]
I found the fix and it's really dumb.

This line:
https://github.com/mueslimak3r/tv-intro-detection/blob/ccbc50f9060ea2ddf67bd476cd9285a3a8aa8c06/decode.py#L105

k started at 0 which meant that while it was intended to search back to front so it would be total # of frames - k frames, doing [-k:] when k is 0 was actually [0:] (front to back). By changing the loop to start at 1 instead, it now actually searches back to front.

**Comment by mueslimak3r** [comment]
I did test against Fresh Prince of Bel Air season 1 and it's almost completely spot on. All but 3 episodes were correct, and the remaining ones were invalidated (set to 0-0 so they wouldn't cause any skipping).

The issue with those is a fairly common issue where the average duration of the matched intro is slightly shorter than the real duration, and a few episodes match the full duration of the intro so are accurate, but are still rejected due to being too far from the average.

So for instance episode 1 & 2 were correctly matched but were too far from the average and rejected.

Overall, having a few rejected is okay for now, and is much preferable to incorrect timestamps that cause skipping random parts of a video

**Comment by mueslimak3r** [comment]
The other thing about batman is that since season on has 60 episodes, it's skipped by default since it has more than the 30 episode cap that's default. It's adjustable in the code rn but I may up that number and/or make it adjustable via an environment variable or cli parameter

**Comment by Fallenbagel** [comment]
> The other thing about batman is that since season one has 60 episodes, it's skipped by default since it has more than the 30 episode cap that's default. It's adjustable in the code rn but I may up that number and/or make it adjustable via an environment variable or cli parameter

Oh I have the dvd version so only 29 episodes per season. I tested batman last night. It was spot on!

**Comment by Fallenbagel** [comment]
> I did test against Fresh Prince of Bel Air season 1 and it's almost completely spot on. All but 3 episodes were correct, and the remaining ones were invalidated (set to 0-0 so they wouldn't cause any skipping).
> 
> The issue with those is a fairly common issue where the average duration of the matched intro is slightly shorter than the real duration, and a few episodes match the full duration of the intro so are accurate, but are still rejected due to being too far from the average.
> 
> So for instance episode 1 & 2 were correctly matched but were too far from the average and rejected.
> 
> Overall, having a few rejected is okay for now, and is much preferable to incorrect timestamps that cause skipping random parts of a video

I havent tested fresh prince yet I'll test and let you know. Since the last update it's been going real good so far. Very accurate (esp batman)
