### ISSUE TITLE
Ignore certain series?

### ISSUE THREAD

**Issue by Yankees4life** [mueslimak3r/tv-intro-detection#15]
Anyway to get this to ignore a certain series. Some series in my folder are just sports shows and game shows really and I don't need to skip the intros of that. I don't keep them often in my drive so its usually just one or two. I would like for this tool to skip that in order to not waste any time processing...

**Comment by mueslimak3r** [comment]
Yeah I can add this. A common way to handle this is have an empty file called `.ignore` in a directory that's being checked. So in a series or season folder you'd put one of these files. Does that sound like a convenient solution?

If so, I'd probably go with something like `.ignore-intros`

**Comment by Yankees4life** [comment]
Yeah...that could probably work.

**Comment by mueslimak3r** [comment]
done. let me know if you have any issues with the implementation
