### ISSUE TITLE
Skipping shows with reason - "failed to access some of the media files"

### ISSUE THREAD

**Issue by saket1999** [mueslimak3r/tv-intro-detection#29]
**Describe the bug**
jellyfin.py is skipping shows with reason "failed to access some of the media files". All the dependencies are installed for jellyfin.py and python version requirement is met.

**To Reproduce**
1. Export the credentials and url
2. start jellyfin.py with arguments "-j -v -l -d"
3. See error

**Logs**
ira@ira:~/tv-intro-detection$ ./jellyfin.py -j -v -l -d

started new session at 2022-06-21 09:15:20.546242

path maps: []
jellyfin has 36 shows
skipping season [Season 1] of show [Ms. Marvel] - failed to access some of the media files
path for the first episode [/srv/dev-disk-by-uuid-17103653-6aa7-4f33-8fa1-05e4a6c231e1/Media/Series/Ms. Marvel (2022)/Season 1/Ms. Marvel - S01E01 - Generation Why WEBDL-1080p.mkv]
skipping season [Season 1] of show [Great Pretender] - failed to access some of the media files
path for the first episode [/srv/dev-disk-by-uuid-17103653-6aa7-4f33-8fa1-05e4a6c231e1/Media/Anime/Great Pretender (2020)/Season 1/Great Pretender - S01E01 - Case 1_1 - Los Angeles Connection HDTV-1080p.mkv]
skipping season [Season 2] of show [Great Pretender] - failed to access some of the media files
path for the first episode [/srv/dev-disk-by-uuid-17103653-6aa7-4f33-8fa1-05e4a6c231e1/Media/Anime/Great Pretender (2020)/Season 2/Great Pretender - S02E01 - Case 4_1 - Wizard of Far East HDTV-1080p.mkv]
skipping season [Season 1] of show [Mushoku Tensei: Jobless Reincarnation] - failed to access some of the media files
path for the first episode [/srv/dev-disk-by-uuid-17103653-6aa7-4f33-8fa1-05e4a6c231e1/Media/Anime/Mushoku Tensei - Jobless Reincarnation (2021)/Season 1/Mushoku Tensei - Jobless Reincarnation - S01E01 - Jobless Reincarnation HDTV-1080p Proper.mkv]
skipping season [Season 1] of show [Moon Knight] - failed to access some of the media files
path for the first episode [/srv/dev-disk-by-uuid-17103653-6aa7-4f33-8fa1-05e4a6c231e1/Media/Series/Moon Knight (2022)/Season 1/Moon Knight - S01E01 - TBA WEBDL-1080p.mkv]
skipping season [Season 1] of show [Westworld] - failed to access some of the media files
path for the first episode [/srv/dev-disk-by-uuid-17103653-6aa7-4f33-8fa1-05e4a6c231e1/Media/Series/Westworld (2016)/Season 1/Westworld - S01E01 - The Original Bluray-1080p.mkv]
skipping season [Season 2] of show [Westworld] - failed to access some of the media files
path for the first episode [/srv/dev-disk-by-uuid-17103653-6aa7-4f33-8fa1-05e4a6c231e1/Media/Series/Westworld (2016)/Season 2/Westworld - S02E01 - Journey into Night Bluray-1080p.mkv]
skipping season [Season 3] of show [Westworld] - failed to access some of the media files
path for the first episode [/srv/dev-disk-by-uuid-17103653-6aa7-4f33-8fa1-05e4a6c231e1/Media/Series/Westworld (2016)/Season 3/Westworld - S03E01 - Parce Domine Bluray-1080p.mkv]
skipping season [Season 1] of show [Narcos] - failed to access some of the media files
path for the first episode [/srv/dev-disk-by-uuid-17103653-6aa7-4f33-8fa1-05e4a6c231e1/Media/Series/Narcos (2015)/Season 1/Narcos - S01E01 - Descenso Bluray-1080p.mp4]
skipping season [Season 2] of show [Narcos] - failed to access some of the media files
path for the first episode [/srv/dev-disk-by-uuid-17103653-6aa7-4f33-8fa1-05e4a6c231e1/Media/Series/Narcos (2015)/Season 2/Narcos - S02E01 - Free at Last Bluray-1080p.mp4]
skipping season [Season 3] of show [Narcos] - failed to access some of the media files
path for the first episode [/srv/dev-disk-by-uuid-17103653-6aa7-4f33-8fa1-05e4a6c231e1/Media/Series/Narcos (2015)/Season 3/Narcos - S03E01 - The Kingpin Strategy Bluray-1080p.mp4]
skipping season [Season 1] of show [Sherlock] - failed to access some of the media files
path for the first episode [/srv/dev-disk-by-uuid-17103653-6aa7-4f33-8fa1-05e4a6c231e1/Media/Series/Sherlock (2010)/Season 1/Sherlock - S01E01 - A Study in Pink Bluray-1080p.mkv]
skipping season [Season 2] of show [Sherlock] - failed to access some of the media files
path for the first episode [/srv/dev-disk-by-uuid-17103653-6aa7-4f33-8fa1-05e4a6c231e1/Media/Series/Sherlock (2010)/Season 2/Sherlock - S02E01 - A Scandal in Belgravia Bluray-1080p.mkv]
skipping season [Season 3] of show [Sherlock] - failed to access some of the media files
path for the first episode [/srv/dev-disk-by-uuid-17103653-6aa7-4f33-8fa1-05e4a6c231e1/Media/Series/Sherlock (2010)/Season 3/Sherlock - S03E01 - The Empty Hearse Bluray-1080p.mkv]
skipping season [Season 4] of show [Sherlock] - failed to access some of the media files
path for the first episode [/srv/dev-disk-by-uuid-17103653-6aa7-4f33-8fa1-05e4a6c231e1/Media/Series/Sherlock (2010)/Season 4/Sherlock - S04E01 - The Six Thatchers Bluray-1080p.mkv]
skipping season [Season 1] of show [Stranger Things] - failed to access some of the media files
path for the first episode [/srv/dev-disk-by-uuid-17103653-6aa7-4f33-8fa1-05e4a6c231e1/Media/Series/Stranger Things (2016)/Season 1/Stranger Things - S01E01 - Chapter One - The Vanishing of Will Byers Bluray-1080p.mkv]
skipping season [Season 2] of show [Stranger Things] - failed to access some of the media files
path for the first episode [/srv/dev-disk-by-uuid-17103653-6aa7-4f33-8fa1-05e4a6c231e1/Media/Series/Stranger Things (2016)/Season 2/Stranger Things - S02E01 - Chapter One - MADMAX Bluray-1080p.mkv]
skipping season [Season 3] of show [Stranger Things] - failed to access some of the media files
path for the first episode [/srv/dev-disk-by-uuid-17103653-6aa7-4f33-8fa1-05e4a6c231e1/Media/Series/Stranger Things (2016)/Season 3/Stranger Things - S03E01 - Chapter One - Suzie, Do You Copy WEBDL-1080p.mkv]
skipping season [Season 4] of show [Stranger Things] - failed to access some of the media files
path for the first episode [/srv/dev-disk-by-uuid-17103653-6aa7-4f33-8fa1-05e4a6c231e1/Media/Series/Stranger Things (2016)/Season 4/Stranger Things - S04E01 - Chapter One - The Hellfire Club WEBDL-1080p.mkv]
skipping season [Season 1] of show [True Detective] - failed to access some of the media files
path for the first episode [/srv/dev-disk-by-uuid-17103653-6aa7-4f33-8fa1-05e4a6c231e1/Media/Series/True Detective (2014)/Season 1/True Detective - S01E01 - The Long Bright Dark Bluray-1080p.mkv]
skipping season [Season 2] of show [True Detective] - failed to access some of the media files
path for the first episode [/srv/dev-disk-by-uuid-17103653-6aa7-4f33-8fa1-05e4a6c231e1/Media/Series/True Detective (2014)/Season 2/True Detective - S02E01 - The Western Book of the Dead Bluray-1080p.mkv]
skipping season [Season 3] of show [True Detective] - failed to access some of the media files
path for the first episode [/srv/dev-disk-by-uuid-17103653-6aa7-4f33-8fa1-05e4a6c231e1/Media/Series/True Detective (2014)/Season 3/True Detective - S03E01 - The Great War and Modern Memory Bluray-1080p.mkv]
skipping season [Season 1] of show [Mindhunter] - failed to access some of the media files
path for the first episode [/srv/dev-disk-by-uuid-17103653-6aa7-4f33-8fa1-05e4a6c231e1/Media/Series/MINDHUNTER (2017)/Season 1/MINDHUNTER - S01E01 - Episode 1 WEBRip-1080p.mkv]
skipping season [Season 2] of show [Mindhunter] - failed to access some of the media files
path for the first episode [/srv/dev-disk-by-uuid-17103653-6aa7-4f33-8fa1-05e4a6c231e1/Media/Series/MINDHUNTER (2017)/Season 2/MINDHUNTER - S02E01 - Episode 1 WEBDL-1080p.mkv]
skipping season [Season 1] of show [The Falcon and the Winter Soldier] - failed to access some of the media files
path for the first episode [/srv/dev-disk-by-uuid-17103653-6aa7-4f33-8fa1-05e4a6c231e1/Media/Series/The Falcon and the Winter Soldier (2021)/Season 1/The Falcon and the Winter Soldier - S01E01 - New World Order WEBDL-1080p Proper.mkv]
skipping season [Season 1] of show [WandaVision] - failed to access some of the media files
path for the first episode [/srv/dev-disk-by-uuid-17103653-6aa7-4f33-8fa1-05e4a6c231e1/Media/Series/WandaVision (2021)/Season 1/WandaVision - S01E01 - Filmed Before a Live Studio Audience WEBDL-1080p.mkv]
skipping season [Season 1] of show [Hawkeye] - failed to access some of the media files
path for the first episode [/srv/dev-disk-by-uuid-17103653-6aa7-4f33-8fa1-05e4a6c231e1/Media/Series/Hawkeye (2021)/Season 1/Hawkeye (2021) - S01E01 - Never Meet Your Heroes WEBDL-1080p.mkv]
skipping season [Season 1] of show [Loki] - failed to access some of the media files
path for the first episode [/srv/dev-disk-by-uuid-17103653-6aa7-4f33-8fa1-05e4a6c231e1/Media/Series/Loki (2021)/Season 1/Loki - S01E01 - Glorious Purpose WEBRip-1080p Proper.mkv]
skipping season [Season 1] of show [Invincible] - failed to access some of the media files
path for the first episode [/srv/dev-disk-by-uuid-17103653-6aa7-4f33-8fa1-05e4a6c231e1/Media/Series/Invincible (2021)/Season 1/Invincible (2021) - S01E01 - IT’S ABOUT TIME WEBDL-1080p Proper.mkv]
skipping season [Season 1] of show [Upload] - failed to access some of the media files
path for the first episode [/srv/dev-disk-by-uuid-17103653-6aa7-4f33-8fa1-05e4a6c231e1/Media/Series/Upload (2020)/Season 1/Upload - S01E01 - Welcome to Upload WEBDL-1080p Proper.mkv]
skipping season [Season 2] of show [Upload] - failed to access some of the media files
path for the first episode [/srv/dev-disk-by-uuid-17103653-6aa7-4f33-8fa1-05e4a6c231e1/Media/Series/Upload (2020)/Season 2/Upload - S02E01 - Welcome Back, Mr. Brown WEBDL-1080p.mkv]
skipping season [Season 1] of show [Beyblade: Metal Fusion] - failed to access some of the media files
path for the first episode [/srv/dev-disk-by-uuid-17103653-6aa7-4f33-8fa1-05e4a6c231e1/Media/Series/Metal Fight Beyblade (2009)/Season 01/Episode S01E01.MP4]
skipping season [Season 2] of show [Beyblade: Metal Fusion] - failed to access some of the media files
path for the first episode [/srv/dev-disk-by-uuid-17103653-6aa7-4f33-8fa1-05e4a6c231e1/Media/Series/Metal Fight Beyblade (2009)/Season 02/Episode S02E01.MP4]
skipping season [Season 3] of show [Beyblade: Metal Fusion] - failed to access some of the media files
path for the first episode [/srv/dev-disk-by-uuid-17103653-6aa7-4f33-8fa1-05e4a6c231e1/Media/Series/Metal Fight Beyblade (2009)/Season 03/Episode S03E01.MP4]
skipping season [Season 4] of show [Beyblade: Metal Fusion] - failed to access some of the media files
path for the first episode [/srv/dev-disk-by-uuid-17103653-6aa7-4f33-8fa1-05e4a6c231e1/Media/Series/Metal Fight Beyblade (2009)/Season 04/Episode S04E01.mkv]
skipping season [Season 1] of show [House of Cards] - failed to access some of the media files
path for the first episode [/srv/dev-disk-by-uuid-17103653-6aa7-4f33-8fa1-05e4a6c231e1/Media/Series/House of Cards (2013)/Season 1/House.of.Cards.2013.S01E01.720p.BluRay.2CH.x265.HEVC.Dubbed.FA-[My-Film].mkv]
skipping season [Season 2] of show [House of Cards] - failed to access some of the media files
path for the first episode [/srv/dev-disk-by-uuid-17103653-6aa7-4f33-8fa1-05e4a6c231e1/Media/Series/House of Cards (2013)/Season 2/House.of.Cards.2013.S02E01.720p.BluRay.2CH.x265.HEVC.Dubbed.FA-[My-Film].mkv]
skipping season [Season 3] of show [House of Cards] - failed to access some of the media files
path for the first episode [/srv/dev-disk-by-uuid-17103653-6aa7-4f33-8fa1-05e4a6c231e1/Media/Series/House of Cards (2013)/Season 3/House.of.Cards.2013.S03E01.720p.BluRay.2CH.x265.HEVC.Dubbed.FA-[My-Film].mkv]
skipping season [Season 4] of show [House of Cards] - failed to access some of the media files
path for the first episode [/srv/dev-disk-by-uuid-17103653-6aa7-4f33-8fa1-05e4a6c231e1/Media/Series/House of Cards (2013)/Season 4/House.of.Cards.2013.S04E01.720p.BluRay.2CH.x265.HEVC.Dubbed.FA-[My-Film].mkv]
skipping season [Season 5] of show [House of Cards] - failed to access some of the media files
path for the first episode [/srv/dev-disk-by-uuid-17103653-6aa7-4f33-8fa1-05e4a6c231e1/Media/Series/House of Cards (2013)/Season 5/House.of.Cards.2013.S05E01.720p.WEBRip.2CH.x265.HEVC-[My-Film].mkv]
skipping season [Season 6] of show [House of Cards] - failed to access some of the media files
path for the first episode [/srv/dev-disk-by-uuid-17103653-6aa7-4f33-8fa1-05e4a6c231e1/Media/Series/House of Cards (2013)/Season 6/house.of.cards.s06e01.720p.bluray.x264-pahe.in.mkv]
skipping season [Season 1] of show [Ben 10: Omniverse] - failed to access some of the media files
path for the first episode [/srv/dev-disk-by-uuid-17103653-6aa7-4f33-8fa1-05e4a6c231e1/Media/Series/Ben 10 Omniverse (2012)/Season 01/Episode S01E01.mkv]
skipping season [Season 2] of show [Ben 10: Omniverse] - failed to access some of the media files
path for the first episode [/srv/dev-disk-by-uuid-17103653-6aa7-4f33-8fa1-05e4a6c231e1/Media/Series/Ben 10 Omniverse (2012)/Season 02/Episode S02E01.mkv]
skipping season [Season 3] of show [Ben 10: Omniverse] - failed to access some of the media files
path for the first episode [/srv/dev-disk-by-uuid-17103653-6aa7-4f33-8fa1-05e4a6c231e1/Media/Series/Ben 10 Omniverse (2012)/Season 03/Episode S03E01.mkv]
skipping season [Season 4] of show [Ben 10: Omniverse] - failed to access some of the media files
path for the first episode [/srv/dev-disk-by-uuid-17103653-6aa7-4f33-8fa1-05e4a6c231e1/Media/Series/Ben 10 Omniverse (2012)/Season 04/Episode S04E01.mp4]
skipping season [Season 5] of show [Ben 10: Omniverse] - failed to access some of the media files
path for the first episode [/srv/dev-disk-by-uuid-17103653-6aa7-4f33-8fa1-05e4a6c231e1/Media/Series/Ben 10 Omniverse (2012)/Season 05/Episode S05E01.mkv]
skipping season [Season 6] of show [Ben 10: Omniverse] - failed to access some of the media files
path for the first episode [/srv/dev-disk-by-uuid-17103653-6aa7-4f33-8fa1-05e4a6c231e1/Media/Series/Ben 10 Omniverse (2012)/Season 06/Episode S06E01.mkv]
skipping season [Season 7] of show [Ben 10: Omniverse] - failed to access some of the media files
path for the first episode [/srv/dev-disk-by-uuid-17103653-6aa7-4f33-8fa1-05e4a6c231e1/Media/Series/Ben 10 Omniverse (2012)/Season 07/Episode S07E01.mkv]
skipping season [Season 8] of show [Ben 10: Omniverse] - failed to access some of the media files
path for the first episode [/srv/dev-disk-by-uuid-17103653-6aa7-4f33-8fa1-05e4a6c231e1/Media/Series/Ben 10 Omniverse (2012)/Season 08/Episode S08E01.mkv]
skipping season [Season 1] of show [Ben 10: Ultimate Alien] - failed to access some of the media files
path for the first episode [/srv/dev-disk-by-uuid-17103653-6aa7-4f33-8fa1-05e4a6c231e1/Media/Series/Ben 10 Ultimate Alien (2010)/Season 01/Episode S01E01.mp4]
skipping season [Season 2] of show [Ben 10: Ultimate Alien] - failed to access some of the media files
path for the first episode [/srv/dev-disk-by-uuid-17103653-6aa7-4f33-8fa1-05e4a6c231e1/Media/Series/Ben 10 Ultimate Alien (2010)/Season 02/Episode S02E01.mp4]
skipping season [Season 3] of show [Ben 10: Ultimate Alien] - failed to access some of the media files
path for the first episode [/srv/dev-disk-by-uuid-17103653-6aa7-4f33-8fa1-05e4a6c231e1/Media/Series/Ben 10 Ultimate Alien (2010)/Season 03/Episode S03E01.mp4]
skipping season [Season 1] of show [Ben 10: Alien Force] - failed to access some of the media files
path for the first episode [/srv/dev-disk-by-uuid-17103653-6aa7-4f33-8fa1-05e4a6c231e1/Media/Series/Ben 10 - Alien Force (2008)/Season 1/Ben 10 - Alien Force - S01E01 - Ben 10 Returns (1) HDTV-720p.mp4]
skipping season [Season 2] of show [Ben 10: Alien Force] - failed to access some of the media files
path for the first episode [/srv/dev-disk-by-uuid-17103653-6aa7-4f33-8fa1-05e4a6c231e1/Media/Series/Ben 10 - Alien Force (2008)/Season 2/Ben 10 - Alien Force - S02E01 - Darkstar Rising HDTV-720p.mp4]
skipping season [Season 3] of show [Ben 10: Alien Force] - failed to access some of the media files
path for the first episode [/srv/dev-disk-by-uuid-17103653-6aa7-4f33-8fa1-05e4a6c231e1/Media/Series/Ben 10 - Alien Force (2008)/Season 3/Ben 10 - Alien Force - S03E01 - Vengeance of Vilgax (1) HDTV-720p.mp4]
skipping season [Season 1] of show [Ben 10] - failed to access some of the media files
path for the first episode [/srv/dev-disk-by-uuid-17103653-6aa7-4f33-8fa1-05e4a6c231e1/Media/Series/Ben 10 (2005)/Season 01/Episode S01E01.mp4]
skipping season [Season 2] of show [Ben 10] - failed to access some of the media files
path for the first episode [/srv/dev-disk-by-uuid-17103653-6aa7-4f33-8fa1-05e4a6c231e1/Media/Series/Ben 10 (2005)/Season 02/Episode S02E01.mp4]
skipping season [Season 3] of show [Ben 10] - failed to access some of the media files
path for the first episode [/srv/dev-disk-by-uuid-17103653-6aa7-4f33-8fa1-05e4a6c231e1/Media/Series/Ben 10 (2005)/Season 03/Episode S03E01.mp4]
skipping season [Season 4] of show [Ben 10] - failed to access some of the media files
path for the first episode [/srv/dev-disk-by-uuid-17103653-6aa7-4f33-8fa1-05e4a6c231e1/Media/Series/Ben 10 (2005)/Season 04/Episode S04E01.mp4]
skipping season [Season 1] of show [The Rising of the Shield Hero] - failed to access some of the media files
path for the first episode [/srv/dev-disk-by-uuid-17103653-6aa7-4f33-8fa1-05e4a6c231e1/Media/Anime/The Rising of the Shield Hero (2019)/Season 1/The Rising of the Shield Hero - S01E01 - The Shield Hero Bluray-1080p.mkv]
skipping season [Season 2] of show [The Rising of the Shield Hero] - failed to access some of the media files
path for the first episode [/srv/dev-disk-by-uuid-17103653-6aa7-4f33-8fa1-05e4a6c231e1/Media/Anime/The Rising of the Shield Hero (2019)/Season 2/The Rising of the Shield Hero - S02E01 - A New Roar HDTV-1080p.mkv]
skipping season [Season 1] of show [The Witcher] - failed to access some of the media files
path for the first episode [/srv/dev-disk-by-uuid-17103653-6aa7-4f33-8fa1-05e4a6c231e1/Media/Series/The Witcher (2019)/Season 1/The Witcher - S01E01 - The End's Beginning WEBDL-1080p REAL.mkv]
skipping season [Season 2] of show [The Witcher] - failed to access some of the media files
path for the first episode [/srv/dev-disk-by-uuid-17103653-6aa7-4f33-8fa1-05e4a6c231e1/Media/Series/The Witcher (2019)/Season 2/The Witcher - S02E01 - A Grain of Truth WEBDL-1080p.mkv]
skipping season [Season 1] of show [My Hero Academia] - failed to access some of the media files
path for the first episode [/srv/dev-disk-by-uuid-17103653-6aa7-4f33-8fa1-05e4a6c231e1/Media/Anime/My Hero Academia (2016)/Season 1/[Judas] Boku no Hero Academia S1 - 01.mkv]
skipping season [Season 2] of show [My Hero Academia] - failed to access some of the media files
path for the first episode [/srv/dev-disk-by-uuid-17103653-6aa7-4f33-8fa1-05e4a6c231e1/Media/Anime/My Hero Academia (2016)/Season 2/My Hero Academia - S02E01 - That's the Idea, Ochaco Bluray-1080p.mkv]
skipping season [Season 3] of show [My Hero Academia] - failed to access some of the media files
path for the first episode [/srv/dev-disk-by-uuid-17103653-6aa7-4f33-8fa1-05e4a6c231e1/Media/Anime/My Hero Academia (2016)/Season 3/My Hero Academia - S03E01 - Game Start WEBDL-1080p.mkv]
skipping season [Season 4] of show [My Hero Academia] - failed to access some of the media files
path for the first episode [/srv/dev-disk-by-uuid-17103653-6aa7-4f33-8fa1-05e4a6c231e1/Media/Anime/My Hero Academia (2016)/Season 4/My Hero Academia - S04E01 - The Scoop on U.A. Class 1-A HDTV-1080p.mkv]
skipping season [Season 5] of show [My Hero Academia] - failed to access some of the media files
path for the first episode [/srv/dev-disk-by-uuid-17103653-6aa7-4f33-8fa1-05e4a6c231e1/Media/Anime/My Hero Academia (2016)/Season 5/My Hero Academia - S05E01 - All Hands on Deck! Class 1-A WEBRip-1080p.mkv]
skipping season [Season 1] of show [What If...?] - failed to access some of the media files
path for the first episode [/srv/dev-disk-by-uuid-17103653-6aa7-4f33-8fa1-05e4a6c231e1/Media/Series/What If…! (2021)/Season 1/What If…! - S01E01 - What If… Captain Carter Were The First Avenger WEBDL-1080p Proper.mkv]
skipping season [Season 1] of show [Tokyo Revengers] - failed to access some of the media files
path for the first episode [/srv/dev-disk-by-uuid-17103653-6aa7-4f33-8fa1-05e4a6c231e1/Media/Anime/Tokyo Revengers (2021)/Season 1/Tokyo Revengers - S01E01 - Reborn WEBRip-1080p.mkv]
skipping season [Season 1] of show [Peacemaker] - failed to access some of the media files
path for the first episode [/srv/dev-disk-by-uuid-17103653-6aa7-4f33-8fa1-05e4a6c231e1/Media/Series/Peacemaker (2022)/Season 1/Peacemaker - S01E01 - A Whole New Whirled WEBDL-1080p.mkv]
skipping season [Season 1] of show [That Time I Got Reincarnated as a Slime] - failed to access some of the media files
path for the first episode [/srv/dev-disk-by-uuid-17103653-6aa7-4f33-8fa1-05e4a6c231e1/Media/Anime/That Time I Got Reincarnated as a Slime/Season 1/That Time I Got Reincarnated as a Slime - S01E01 - The Storm Dragon, Veldora HDTV-1080p.mkv]
skipping season [Season 2] of show [That Time I Got Reincarnated as a Slime] - failed to access some of the media files
path for the first episode [/srv/dev-disk-by-uuid-17103653-6aa7-4f33-8fa1-05e4a6c231e1/Media/Anime/That Time I Got Reincarnated as a Slime/Season 2/[Anime Time] Tensei Shitara Slime Datta Ken (That Time I Got Reincarnated as a Slime) - S02E01 [1080p][HEVC 10bit x265][AAC][Multi Sub].mkv]
skipping season [Season 1] of show [Overlord] - failed to access some of the media files
path for the first episode [/srv/dev-disk-by-uuid-17103653-6aa7-4f33-8fa1-05e4a6c231e1/Media/Anime/Overlord/Season 1/Overlord - S01E01 - End and Beginning Bluray-1080p.mkv]
skipping season [Season 2] of show [Overlord] - failed to access some of the media files
path for the first episode [/srv/dev-disk-by-uuid-17103653-6aa7-4f33-8fa1-05e4a6c231e1/Media/Anime/Overlord/Season 2/Overlord - S02E01 - The Dawn of Despair HDTV-1080p.mkv]
skipping season [Season 3] of show [Overlord] - failed to access some of the media files
path for the first episode [/srv/dev-disk-by-uuid-17103653-6aa7-4f33-8fa1-05e4a6c231e1/Media/Anime/Overlord/Season 3/Overlord - S03E01 - A Ruler's Melancholy HDTV-1080p.mkv]
skipping season [Season 1] of show [Cautious Hero: The Hero Is Overpowered but Overly Cautious] - failed to access some of the media files
path for the first episode [/srv/dev-disk-by-uuid-17103653-6aa7-4f33-8fa1-05e4a6c231e1/Media/Anime/Cautious Hero - The Hero Is Overpowered but Overly Cautious/Season 1/Cautious Hero - The Hero Is Overpowered but Overly Cautious - S01E01 - This Hero is Too Cautious HDTV-1080p.mp4]
skipping season [Specials] of show [The Boys] - failed to access some of the media files
path for the first episode [/srv/dev-disk-by-uuid-17103653-6aa7-4f33-8fa1-05e4a6c231e1/Media/Series/The Boys/Specials/The Boys - S00E01 - Butcher - A Short Film Bluray-1080p.mkv]
skipping season [Season 1] of show [The Boys] - failed to access some of the media files
path for the first episode [/srv/dev-disk-by-uuid-17103653-6aa7-4f33-8fa1-05e4a6c231e1/Media/Series/The Boys/Season 1/The Boys - S01E01 - The Name of the Game HDTV-1080p.mkv]
skipping season [Season 2] of show [The Boys] - failed to access some of the media files
path for the first episode [/srv/dev-disk-by-uuid-17103653-6aa7-4f33-8fa1-05e4a6c231e1/Media/Series/The Boys/Season 2/The Boys - S02E01 - The Big Ride Bluray-1080p.mkv]
skipping season [Season 3] of show [The Boys] - failed to access some of the media files
path for the first episode [/srv/dev-disk-by-uuid-17103653-6aa7-4f33-8fa1-05e4a6c231e1/Media/Series/The Boys/Season 3/The Boys - S03E01 - Payback WEBDL-1080p.mkv]
skipping season [Season 1] of show [One-Punch Man] - failed to access some of the media files
path for the first episode [/srv/dev-disk-by-uuid-17103653-6aa7-4f33-8fa1-05e4a6c231e1/Media/Anime/One-Punch Man/Season 1/One-Punch Man - S01E01 - The Strongest Man HDTV-1080p.mkv]
skipping season [Season 2] of show [One-Punch Man] - failed to access some of the media files
path for the first episode [/srv/dev-disk-by-uuid-17103653-6aa7-4f33-8fa1-05e4a6c231e1/Media/Anime/One-Punch Man/Season 2/One-Punch Man - S02E01 - Return of the Hero HDTV-1080p.mkv]
skipping season [Season 1] of show [The Wheel of Time] - failed to access some of the media files
path for the first episode [/srv/dev-disk-by-uuid-17103653-6aa7-4f33-8fa1-05e4a6c231e1/Media/Series/The Wheel of Time/Season 1/The Wheel of Time - S01E01 - Leavetaking WEBDL-1080p.mkv]
skipping season [Season 1] of show [Attack on Titan] - failed to access some of the media files
path for the first episode [/srv/dev-disk-by-uuid-17103653-6aa7-4f33-8fa1-05e4a6c231e1/Media/Anime/Attack on Titan/Season 1/Attack on Titan - S01E01 - To You, in 2000 Years - The Fall of Shiganshina (1) Bluray-1080p.mkv]
skipping season [Season 2] of show [Attack on Titan] - failed to access some of the media files
path for the first episode [/srv/dev-disk-by-uuid-17103653-6aa7-4f33-8fa1-05e4a6c231e1/Media/Anime/Attack on Titan/Season 2/Attack on Titan - S02E01 - Beast Titan HDTV-1080p.mkv]
skipping season [Season 3] of show [Attack on Titan] - failed to access some of the media files
path for the first episode [/srv/dev-disk-by-uuid-17103653-6aa7-4f33-8fa1-05e4a6c231e1/Media/Anime/Attack on Titan/Season 3/Attack on Titan - S03E01 - Smoke Signal WEBDL-1080p.mkv]
skipping season [Season 4] of show [Attack on Titan] - failed to access some of the media files
path for the first episode [/srv/dev-disk-by-uuid-17103653-6aa7-4f33-8fa1-05e4a6c231e1/Media/Anime/Attack on Titan/Season 4/Attack on Titan - S04E01 - The Other Side of the Sea Bluray-1080p.mkv]
skipping season [Season 1] of show [Demon Slayer: Kimetsu no Yaiba] - failed to access some of the media files
path for the first episode [/srv/dev-disk-by-uuid-17103653-6aa7-4f33-8fa1-05e4a6c231e1/Media/Anime/Demon Slayer - Kimetsu no Yaiba/Season 1/Demon Slayer - Kimetsu no Yaiba - S01E01 - Cruelty HDTV-1080p.mkv]
skipping season [Season 2] of show [Demon Slayer: Kimetsu no Yaiba] - failed to access some of the media files
path for the first episode [/srv/dev-disk-by-uuid-17103653-6aa7-4f33-8fa1-05e4a6c231e1/Media/Anime/Demon Slayer - Kimetsu no Yaiba/Season 2/Demon Slayer - Kimetsu no Yaiba - S02E01 - Flame Hashira Kyojuro Rengoku HDTV-1080p v2.mkv]
skipping season [Season 3] of show [Demon Slayer: Kimetsu no Yaiba] - failed to access some of the media files
path for the first episode [/srv/dev-disk-by-uuid-17103653-6aa7-4f33-8fa1-05e4a6c231e1/Media/Anime/Demon Slayer - Kimetsu no Yaiba/Season 3/Demon Slayer - Kimetsu no Yaiba - S03E01 - Sound Hashira Tengen Uzui HDTV-1080p.mkv]
--<[ session/140671907730096 ]
found 0 qualifying shows
found 0 qualifying seasons
found 0 qualifying episodes

total runtime: 0:00:09.575107
sleeping for 300 seconds

**Comment by mueslimak3r** [comment]
Are you running the script on the same computer that's running jellyfin? And can you verify that the user you're using to run the script has read access to the files &folders where your media is located?

**Comment by saket1999** [comment]
I was running the script in different hyperviser.

**Comment by mueslimak3r** [comment]
> I was running the script in different hyperviser.

The script supports running on a different machine or a different hypervisor. To do this, define the PATH_MAP either as an environment variable or using the path_map.txt file. With this you define the mapping of the path the script would use to access the files to the path that jellyfin uses as. eg: `/mylocalpath/tv::/jellyfinpath/tv`

**Comment by saket1999** [comment]
That seems to be working, I have one more question, Does this script contains file watchdog to look for newly added files or the jellyfin.py needs to be used with cronjob?

**Comment by mueslimak3r** [comment]
> That seems to be working, I have one more question, Does this script contains file watchdog to look for newly added files or the jellyfin.py needs to be used with cronjob?

If you run jellyfin.py with `-j` then it will save to json, and in subsequent runs it will ignore media for which a json dump exists.

Just that basic functionality is included. In the docker image for this project, jellyfin.py is just run repeatedly with a cool down period between. So you could do the same or use a cron job. It is possible that you might run into an issue where if the instance from the prior cron trigger is still running and a new one is started, they both attempt to parse the latest unprocessed media at the same time.

If you do set up a cron job you may want to have a script create a lock file that is deleted when the script exits so you can avoid a situation like that.

I also recommend checking out this other intro skipping project. It's come a long and its audio fingerprinting is much faster than the video fingerprinting I use. Other than rare cases where intros use different music/audio for each episode it should be just as accurate.

https://github.com/ConfusedPolarBear/intro-skipper
