### ISSUE TITLE
Windows Filesystem fix for Windows WSL Setup

### ISSUE THREAD

**Issue by DevilsDesigns** [mueslimak3r/tv-intro-detection#9]
**Describe the bug**

**To Reproduce**
1. `pip install -r requirments.txt` inside wsl2 Ubuntu 20.04
2.  edit the config in `C:\Tools\tv-intro-detection\config\path_map.txt` to show /mnt/j/TV-Shows : /mnt/m/TV-Shows
3. `export JELLYFIN_URL="http://192.168.1.111:8096" && export JELLYFIN_USERNAME="username" && export JELLYFIN_PASSWORD="mypassword"`
4. `python3 jellyfin.py -j -d -l`

**Expected behavior**
Runs through all tv shows in the directories specified in path_map.txt

**Additional context**
Errors on read because of windows Filesystems
```
63/190 - Blue's Clues
1/5 - Season 1 - 2 episodes
started at 2022-04-04 21:01:55.434579
Check Frame: 10

input files invalid or cannot be accessed
no results - the decoder may not have access to the specified media files
processed season [Season 1] in 0:00:00.016687
Received signal: 2
will stop
processed show [Blue's Clues] in 0:00:02.024777
total runtime: 0:05:49.727606
```

**Comment by mueslimak3r** [comment]
> Runs through all tv shows in the directories specified in path_map.txt

As explained on matrix, path_map isn't used to define a list of directories to search in.

It says "given mapping x:y rename x to y" this way if according to jellyfin the file is at x/subdirectory/file.mp4 but the script would find it at y/subdirectory/file.mp4 it can translate those paths

**Comment by mueslimak3r** [comment]
Tested and working with powershell (no wsl needed but it should work). I installed ffmpeg and the latest python version for testing.

**Comment by DevilsDesigns** [comment]
thank you for the fast response and work you rock!

**Comment by DevilsDesigns** [comment]
i keep gettting a weird error when trying to run the jellyfin.py 
![image](https://user-images.githubusercontent.com/35183970/161835915-508b3dbf-bc8f-484c-96a1-3ba8de663e10.png)
Any ideas on what may be wrong
